name: Playground

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    env:
      PNPM_VERSION: '10.33.0'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.8
        with:
          run_install: |
            cwd: ./
            args: [--frozen-lockfile]
          version: ${{ env.PNPM_VERSION }}

      - name: Configure pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build playground
        env:
          PLAYGROUND_BASE_PATH: '${{ steps.pages.outputs.base_path }}'
        run: pnpm build:playground

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist-playground

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4